#ifndef USHI_INCLUDE_USHI_IMPL_ENTITY_OBSERVER_HPP
#define USHI_INCLUDE_USHI_IMPL_ENTITY_OBSERVER_HPP

#include "Core/Core.hpp"

namespace ushi {} // namespace ushi

#endif // USHI_INCLUDE_USHI_IMPL_ENTITY_OBSERVER_HPP
